{
 "title": "DNS-Server",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Internet Bandwidth Saved",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (sum_over_time({filename=\"/harddisk/logs/access.log\"} | json | unwrap body_bytes_sent [7d]))"
    }
   ]
  },
  {
   "title": "Cache Domain",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by(domain) (count_over_time({filename=\"/harddisk/logs/access.log\"} | json | __error__=`` [1d])))",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Top 10 Visitor IP",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "topk(10, sum by(client_ip) (count_over_time({filename=\"/harddisk/logs/access.log\"} | json | __error__=`` [1d])))",
     "legendFormat": "{{client_ip}}"
    }
   ]
  },
  {
   "title": "Cache Ratio",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(upstream_cache_status) (count_over_time({filename=\"/harddisk/logs/access.log\"} | json | __error__=`` [1d]))",
     "legendFormat": "{{upstream_cache_status}}"
    }
   ]
  },
  {
   "title": "Cache Served Per IP",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(client_ip) (sum_over_time({filename=\"/harddisk/logs/access.log\"} | json | unwrap body_bytes_sent | __error__=`` [1d]))",
     "legendFormat": "{{client_ip}}"
    }
   ]
  }
 ]
}