{
 "title": "Mikrotik SysLogs",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Router",
    "query": {}
   },
   {
    "name": "topics",
    "label": "Topics",
    "query": "account,system,critical,firewall,error,warning,interface,ssh,health,wireless"
   },
   { "name": "search", "label": "Search" },
   { "name": "smooth", "label": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h,2h" }
  ]
 },
 "panels": [
  {
   "title": "Log Counts By Topic",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"$job\"} [$__interval] |~\"(?i)$topics\" |~\"(?i)$search\" !~\"(?i)$exclude\")",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "Log Counts By Topic Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({job=\"$job\"} [$__interval] |regexp \"(?P<prefix>\\\\w+)\\\\: \" |~\"(?i)$topics\" |~\"(?i)$search\" !~\"(?i)$exclude\")",
     "legendFormat": "{{prefix}}"
    }
   ]
  },
  {
   "title": "Logs Lines By Topic",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{job=\"$job\"} |~\"(?i)$topics\" |~\"(?i)$search\" !~\"(?i)$exclude\""
    }
   ]
  }
 ]
}