{
 "title": "Mikrotik",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Users",
    "query": "show tag values from \"snmp-interfaces\" with key=\"if-name\""
   },
   {
    "name": "Queues",
    "query": "show tag values from \"snmp-queue-simple\" with key=\"mtxrQueueSimpleName\""
   },
   {
    "name": "times",
    "label": "Interval",
    "query": "10m,15m,30m,1h,,2h,3h,6h,12h,1d,2d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT mean(\"uptime\")/100 FROM \"snmp\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" }
     ]
    }
   ]
  },
  {
   "title": "RAM USED",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp-memory-usage",
     "select": [
      [
       { "params": [ "used-memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" },
      { "condition": "AND", "key": "memory-name", "operator": "=", "value": "main memory" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT last(\"cpu-load\") FROM \"snmp\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu-load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT mean(\"temperature\")/10 FROM \"snmp\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "processor-temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT mean(\"processor-temperature\")/10 FROM \"snmp\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "processor-temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" }
     ]
    }
   ]
  },
  {
   "title": "FAN-1 SPEED",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "FAN SPEED-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT mean(\"fan-speed\") FROM \"snmp\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "fan-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" }
     ]
    }
   ]
  },
  {
   "title": "FAN-2 SPEED",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "fan-speed2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" }
     ]
    }
   ]
  },
  { "title": "WAN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "INTERNET-IN/OUT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp-interfaces",
     "query": "SELECT non_negative_derivative(last(\"bytes-in\"), 1s)*8 FROM \"snmp-interfaces\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria' AND \"if-name\" = '01.Speed-Internet-714') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes-in" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes-out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Upload" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" },
      { "condition": "AND", "key": "if-name", "operator": "=", "value": "01.Speed-Internet-714" }
     ]
    }
   ]
  },
  {
   "title": "GGC-IN/OUT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp-interfaces",
     "query": "SELECT non_negative_derivative(last(\"bytes-in\"), 1s)*8 FROM \"snmp-interfaces\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria' AND \"if-name\" = '02.Speed-GGC-715') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes-in" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes-out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Upload" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" },
      { "condition": "AND", "key": "if-name", "operator": "=", "value": "02.Speed-GGC-715" }
     ]
    }
   ]
  },
  {
   "title": "FNA-IN/OUT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp-interfaces",
     "query": "SELECT non_negative_derivative(last(\"bytes-in\"), 1s)*8 FROM \"snmp-interfaces\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria' AND \"if-name\" = '03.Speed-FNA-716') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes-in" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes-out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Upload" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" },
      { "condition": "AND", "key": "if-name", "operator": "=", "value": "03.Speed-FNA-716" }
     ]
    }
   ]
  },
  {
   "title": "BDIX-IN/OUT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp-interfaces",
     "query": "SELECT non_negative_derivative(last(\"bytes-in\"), 1s)*8 FROM \"snmp-interfaces\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria' AND \"if-name\" = '04.Speed-BDIX-717') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes-in" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes-out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Upload" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" },
      { "condition": "AND", "key": "if-name", "operator": "=", "value": "04.Speed-BDIX-717" }
     ]
    }
   ]
  },
  {
   "title": "Ping/Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "google.com",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "average_response_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=", "value": "google.com" }
       ]
      }
     ]
    },
    {
     "title": "youtube.com",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "average_response_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=", "value": "youtube.com" }
       ]
      }
     ]
    },
    {
     "title": "facebook.com",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "average_response_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=", "value": "facebook.com" }
       ]
      }
     ]
    },
    {
     "title": "twitter.com",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "average_response_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=", "value": "twitter.com" }
       ]
      }
     ]
    },
    {
     "title": "amd.com",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "average_response_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=", "value": "amd.com" }
       ]
      }
     ]
    },
    {
     "title": "gateway",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "average_response_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "=", "value": "192.168.100.241" }
       ]
      }
     ]
    },
    {
     "title": "Average Response Time (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "url" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "average_response_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Packet Loss (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "url" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "percent_packet_loss" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "LAN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bandwidth $Users ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "if-name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snmp-interfaces",
       "query": "SELECT non_negative_derivative(last(\"bytes-out\"), 1s)*8 FROM \"snmp-interfaces\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria' AND \"if-name\" =~ /^$user$/) AND $timeFilter GROUP BY time($__interval), \"if-name\" fill(null)",
       "select": [
        [
         { "params": [ "bytes-out" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "Download" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes-in" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "Upload" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" },
        { "condition": "AND", "key": "if-name", "operator": "=~", "value": "/^$Users$/" }
       ]
      }
     ]
    },
    {
     "title": "Sort By Speed",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "if-name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "limit": "1",
       "measurement": "snmp-interfaces",
       "select": [
        [
         { "params": [ "bytes-out" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "Download" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes-in" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "Upload" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" }
       ]
      }
     ]
    },
    {
     "title": "Link Status- $Users",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$times" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snmp-interfaces",
       "select": [
        [
         { "params": [ "oper-status" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Status" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" },
        { "condition": "AND", "key": "if-name", "operator": "=~", "value": "/^$Users$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Queues",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_mtxrQueueSimpleName Download",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snmp-queue-simple",
       "query": "SELECT non_negative_derivative(last(\"mtxrQueueSimpleBytesIn\"), 1s)*8 FROM \"snmp-queue-simple\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria' AND \"mtxrQueueSimpleName\" =~ /^$Queues$/) AND $timeFilter GROUP BY time($__interval), \"mtxrQueueSimpleName\" fill(null)",
       "select": [
        [
         { "params": [ "mtxrQueueSimpleBytesIn" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "Download" ], "type": "alias" }
        ],
        [
         { "params": [ "mtxrQueueSimpleBytesOut" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "Upload" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" },
        { "condition": "AND", "key": "mtxrQueueSimpleName", "operator": "=~", "value": "/^$Queues$/" }
       ]
      }
     ]
    },
    {
     "title": "Sort By Speed (Queues)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "mtxrQueueSimpleName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "limit": "1",
       "measurement": "snmp-queue-simple",
       "select": [
        [
         { "params": [ "mtxrQueueSimpleBytesIn" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "Download" ], "type": "alias" }
        ],
        [
         { "params": [ "mtxrQueueSimpleBytesOut" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "Upload" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "System Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "Used RAM",
       "query": "SELECT mean(\"used-memory\")/1024 FROM \"snmp-memory-usage\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria' AND \"memory-name\" = 'main memory') AND $timeFilter GROUP BY time($__interval) fill(null)"
      },
      {
       "alias": "Total RAM",
       "query": "SELECT mean(\"total-memory\")/1024 FROM \"snmp-memory-usage\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria' AND \"memory-name\" = 'main memory') AND $timeFilter GROUP BY time($__interval) fill(null)"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "CPU:",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snmp",
       "query": "SELECT mean(\"used-memory\") FROM \"snmp-memory-usage\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria' AND \"memory-name\" = 'main memory') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "cpu-load" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" }
       ]
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "temperature",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snmp",
       "query": "SELECT mean(\"temperature\")/10 FROM \"snmp\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "temperature" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" }
       ]
      },
      {
       "alias": "processor-temperature",
       "query": "SELECT mean(\"processor-temperature\")/10 FROM \"snmp\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria') AND $timeFilter GROUP BY time($__interval) fill(null)"
      }
     ]
    },
    {
     "title": "FAN SPEED",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "yaxes": [
      { "format": "rotrpm" }
     ],
     "targets": [
      {
       "alias": "FAN-1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snmp",
       "query": "SELECT mean(\"fan-speed\") FROM \"snmp\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "fan-speed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=", "value": "SpeedNet-POP-Dumuria" }
       ]
      },
      {
       "alias": "FAN-2",
       "query": "SELECT mean(\"fan-speed2\") FROM \"snmp\" WHERE (\"hostname\" = 'SpeedNet-POP-Dumuria') AND $timeFilter GROUP BY time($__interval) fill(null)"
      }
     ]
    }
   ]
  }
 ]
}